# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ECE532/GITHUB_PRO/ECE532-project/Trumpet_project/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_FFT_wrapper_0_0/design_1_FFT_wrapper_0_0.xci
# IP: The module: 'design_1_FFT_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ECE532/GITHUB_PRO/ECE532-project/Trumpet_project/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_FFT_wrapper_0_0/src/MEM_I_axi_bram_ctrl_0_bram_0/MEM_I_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MEM_I_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==MEM_I_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: c:/ECE532/GITHUB_PRO/ECE532-project/Trumpet_project/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_FFT_wrapper_0_0/src/MEM_I_axi_bram_ctrl_0_bram_0/MEM_I_axi_bram_ctrl_0_bram_0_ooc.xdc

# IP: C:/ECE532/GITHUB_PRO/ECE532-project/Trumpet_project/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_FFT_wrapper_0_0/design_1_FFT_wrapper_0_0.xci
# IP: The module: 'design_1_FFT_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ECE532/GITHUB_PRO/ECE532-project/Trumpet_project/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_FFT_wrapper_0_0/src/MEM_I_axi_bram_ctrl_0_bram_0/MEM_I_axi_bram_ctrl_0_bram_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MEM_I_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==MEM_I_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: c:/ECE532/GITHUB_PRO/ECE532-project/Trumpet_project/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_FFT_wrapper_0_0/src/MEM_I_axi_bram_ctrl_0_bram_0/MEM_I_axi_bram_ctrl_0_bram_0_ooc.xdc
