webtalk_init -webtalk_dir C:/Users/robita46/ECE532-project-main/Trumpet_project/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/i2c_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb  2 21:54:04 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2489853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174111048_179741397_210719908_466" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1708e99e-b261-456d-a639-3afcd3680194" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4f99c4d9c3fa44a9b28699fdfe9410b5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "21010700 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.39_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15164_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3419395785 -regid "174111048_179741397_210719908_466" -xml C:/Users/robita46/ECE532-project-main/Trumpet_project/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/i2c_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/robita46/ECE532-project-main/Trumpet_project/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/i2c_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/robita46/ECE532-project-main/Trumpet_project/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/i2c_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
