# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/HDMI_Transmitter_sub.xci
# IP: The module: 'HDMI_Transmitter_sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/bd_7c6c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c || ORIG_REF_NAME==bd_7c6c} -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_0/bd_7c6c_v_hdmi_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c_v_hdmi_tx_0 || ORIG_REF_NAME==bd_7c6c_v_hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_1/bd_7c6c_v_tc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c_v_tc_0 || ORIG_REF_NAME==bd_7c6c_v_tc_0} -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_2/bd_7c6c_v_axi4s_vid_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c_v_axi4s_vid_out_0 || ORIG_REF_NAME==bd_7c6c_v_axi4s_vid_out_0} -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_3/bd_7c6c_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c_util_vector_logic_0_0 || ORIG_REF_NAME==bd_7c6c_util_vector_logic_0_0} -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_4/bd_7c6c_axi_crossbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c_axi_crossbar_0 || ORIG_REF_NAME==bd_7c6c_axi_crossbar_0} -quiet] -quiet

# XDC: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/bd_7c6c_ooc.xdc

# XDC: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/HDMI_Transmitter_sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMI_Transmitter_sub'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/HDMI_Transmitter_sub.xci
# IP: The module: 'HDMI_Transmitter_sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/bd_7c6c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c || ORIG_REF_NAME==bd_7c6c} -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_0/bd_7c6c_v_hdmi_tx_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c_v_hdmi_tx_0 || ORIG_REF_NAME==bd_7c6c_v_hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_1/bd_7c6c_v_tc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c_v_tc_0 || ORIG_REF_NAME==bd_7c6c_v_tc_0} -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_2/bd_7c6c_v_axi4s_vid_out_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c_v_axi4s_vid_out_0 || ORIG_REF_NAME==bd_7c6c_v_axi4s_vid_out_0} -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_3/bd_7c6c_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c_util_vector_logic_0_0 || ORIG_REF_NAME==bd_7c6c_util_vector_logic_0_0} -quiet] -quiet

# IP: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_4/bd_7c6c_axi_crossbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7c6c_axi_crossbar_0 || ORIG_REF_NAME==bd_7c6c_axi_crossbar_0} -quiet] -quiet

# XDC: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/bd_7c6c_ooc.xdc

# XDC: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/HDMI_Transmitter_sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMI_Transmitter_sub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
