set_property SRC_FILE_INFO {cfile:C:/Users/jason/ECE532/ECE532-project/HDMIDemo_2018.3/vivado_proj/Nexys-Video-HDMI.srcs/constrs_1/imports/constraints/vdma_timing_workaround.xdc rfile:../../../Nexys-Video-HDMI.srcs/constrs_1/imports/constraints/vdma_timing_workaround.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/jason/ECE532/ECE532-project/HDMIDemo_2018.3/vivado_proj/Nexys-Video-HDMI.srcs/constrs_1/imports/constraints/NexysVideo_Master.xdc rfile:../../../Nexys-Video-HDMI.srcs/constrs_1/imports/constraints/NexysVideo_Master.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hierarchical -filter {NAME =~*axi_vdma_0*MM2S*LB_BUILT_IN*/*rstbt*/*rst_reg[*]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hierarchical -filter {NAME =~*axi_vdma_0*MM2S*LB_BUILT_IN*/*rstbt*/*rst_reg_reg}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins -hierarchical -filter {NAME =~*axi_vdma_0*MM2S*LB_BUILT_IN*/*rstbt*/*PRE}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins -hierarchical -filter {NAME =~*axi_vdma_0*S2MM*LB_BUILT_IN*/*rstbt*/*PRE}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hierarchical -filter {NAME =~*axi_vdma_0*S2MM*LB_BUILT_IN*/*rstbt*/*rst_reg_reg && IS_SEQUENTIAL}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hierarchical -filter {NAME =~*axi_vdma_0*S2MM*LB_BUILT_IN*/*rstbt*/*rst_reg[*]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports sys_clk_i]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W4 IOSTANDARD TMDS_33} [get_ports TMDS_IN_clk_n]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD TMDS_33} [get_ports TMDS_IN_clk_p]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS25} [get_ports hdmi_hpd]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y4 IOSTANDARD LVCMOS33} [get_ports DDC_scl_io]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD LVCMOS33} [get_ports DDC_sda_io]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports hdmi_rx_txen]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA3 IOSTANDARD TMDS_33} [get_ports {TMDS_IN_data_n[0]}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y3 IOSTANDARD TMDS_33} [get_ports {TMDS_IN_data_p[0]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y2 IOSTANDARD TMDS_33} [get_ports {TMDS_IN_data_n[1]}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD TMDS_33} [get_ports {TMDS_IN_data_p[1]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD TMDS_33} [get_ports {TMDS_IN_data_n[2]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD TMDS_33} [get_ports {TMDS_IN_data_p[2]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD TMDS_33} [get_ports TMDS_OUT_clk_n]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD TMDS_33} [get_ports TMDS_OUT_clk_p]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y1 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_n[0]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W1 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_p[0]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB1 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_n[1]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_p[1]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_n[2]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_p[2]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports {frequency_input_0[0]}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13 [get_ports {frequency_input_0[1]}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {frequency_input_0[2]}]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {frequency_input_0[3]}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports {frequency_input_0[4]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13 [get_ports {frequency_input_0[5]}]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports {frequency_input_0[6]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {frequency_input_0[7]}]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB22 [get_ports {frequency_input_0[8]}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB21 [get_ports {frequency_input_0[9]}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports {frequency_input_0[10]}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB18 [get_ports {frequency_input_0[11]}]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21 [get_ports {frequency_input_0[12]}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21 [get_ports {frequency_input_0[13]}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20 [get_ports {frequency_input_0[14]}]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA18 [get_ports {frequency_input_0[15]}]
set_property src_info {type:XDC file:2 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[0]}]
set_property src_info {type:XDC file:2 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[1]}]
set_property src_info {type:XDC file:2 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[6]}]
set_property src_info {type:XDC file:2 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[7]}]
set_property src_info {type:XDC file:2 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[9]}]
set_property src_info {type:XDC file:2 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[12]}]
set_property src_info {type:XDC file:2 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[13]}]
set_property src_info {type:XDC file:2 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[14]}]
set_property src_info {type:XDC file:2 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[2]}]
set_property src_info {type:XDC file:2 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[3]}]
set_property src_info {type:XDC file:2 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[4]}]
set_property src_info {type:XDC file:2 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[5]}]
set_property src_info {type:XDC file:2 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[8]}]
set_property src_info {type:XDC file:2 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[10]}]
set_property src_info {type:XDC file:2 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[11]}]
set_property src_info {type:XDC file:2 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/frequency_input[15]}]
set_property src_info {type:XDC file:2 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_araddr[2]}]
set_property src_info {type:XDC file:2 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_araddr[3]}]
set_property src_info {type:XDC file:2 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_awaddr[2]}]
set_property src_info {type:XDC file:2 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_awaddr[3]}]
set_property src_info {type:XDC file:2 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[22]}]
set_property src_info {type:XDC file:2 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[0]}]
set_property src_info {type:XDC file:2 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[2]}]
set_property src_info {type:XDC file:2 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[5]}]
set_property src_info {type:XDC file:2 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[6]}]
set_property src_info {type:XDC file:2 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[21]}]
set_property src_info {type:XDC file:2 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[23]}]
set_property src_info {type:XDC file:2 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[26]}]
set_property src_info {type:XDC file:2 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[31]}]
set_property src_info {type:XDC file:2 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[29]}]
set_property src_info {type:XDC file:2 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[28]}]
set_property src_info {type:XDC file:2 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[1]}]
set_property src_info {type:XDC file:2 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[7]}]
set_property src_info {type:XDC file:2 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[8]}]
set_property src_info {type:XDC file:2 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[12]}]
set_property src_info {type:XDC file:2 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[13]}]
set_property src_info {type:XDC file:2 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[4]}]
set_property src_info {type:XDC file:2 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[3]}]
set_property src_info {type:XDC file:2 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[9]}]
set_property src_info {type:XDC file:2 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[14]}]
set_property src_info {type:XDC file:2 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[15]}]
set_property src_info {type:XDC file:2 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[16]}]
set_property src_info {type:XDC file:2 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[19]}]
set_property src_info {type:XDC file:2 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[25]}]
set_property src_info {type:XDC file:2 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[27]}]
set_property src_info {type:XDC file:2 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[10]}]
set_property src_info {type:XDC file:2 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[11]}]
set_property src_info {type:XDC file:2 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[17]}]
set_property src_info {type:XDC file:2 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[18]}]
set_property src_info {type:XDC file:2 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[20]}]
set_property src_info {type:XDC file:2 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[24]}]
set_property src_info {type:XDC file:2 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[30]}]
set_property src_info {type:XDC file:2 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[2]}]
set_property src_info {type:XDC file:2 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[4]}]
set_property src_info {type:XDC file:2 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[9]}]
set_property src_info {type:XDC file:2 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[11]}]
set_property src_info {type:XDC file:2 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[25]}]
set_property src_info {type:XDC file:2 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[26]}]
set_property src_info {type:XDC file:2 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[3]}]
set_property src_info {type:XDC file:2 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[7]}]
set_property src_info {type:XDC file:2 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[0]}]
set_property src_info {type:XDC file:2 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[15]}]
set_property src_info {type:XDC file:2 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[16]}]
set_property src_info {type:XDC file:2 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[17]}]
set_property src_info {type:XDC file:2 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[22]}]
set_property src_info {type:XDC file:2 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[27]}]
set_property src_info {type:XDC file:2 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[23]}]
set_property src_info {type:XDC file:2 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[24]}]
set_property src_info {type:XDC file:2 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[5]}]
set_property src_info {type:XDC file:2 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[10]}]
set_property src_info {type:XDC file:2 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[12]}]
set_property src_info {type:XDC file:2 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[13]}]
set_property src_info {type:XDC file:2 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[20]}]
set_property src_info {type:XDC file:2 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[21]}]
set_property src_info {type:XDC file:2 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[28]}]
set_property src_info {type:XDC file:2 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[31]}]
set_property src_info {type:XDC file:2 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[1]}]
set_property src_info {type:XDC file:2 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[6]}]
set_property src_info {type:XDC file:2 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[8]}]
set_property src_info {type:XDC file:2 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[14]}]
set_property src_info {type:XDC file:2 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[18]}]
set_property src_info {type:XDC file:2 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[19]}]
set_property src_info {type:XDC file:2 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[29]}]
set_property src_info {type:XDC file:2 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[30]}]
set_property src_info {type:XDC file:2 line:481 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {hdmi_i/frequency_input_0_RnM/frequency_input[0]} {hdmi_i/frequency_input_0_RnM/frequency_input[1]} {hdmi_i/frequency_input_0_RnM/frequency_input[2]} {hdmi_i/frequency_input_0_RnM/frequency_input[3]} {hdmi_i/frequency_input_0_RnM/frequency_input[4]} {hdmi_i/frequency_input_0_RnM/frequency_input[5]} {hdmi_i/frequency_input_0_RnM/frequency_input[6]} {hdmi_i/frequency_input_0_RnM/frequency_input[7]} {hdmi_i/frequency_input_0_RnM/frequency_input[8]} {hdmi_i/frequency_input_0_RnM/frequency_input[9]} {hdmi_i/frequency_input_0_RnM/frequency_input[10]} {hdmi_i/frequency_input_0_RnM/frequency_input[11]} {hdmi_i/frequency_input_0_RnM/frequency_input[12]} {hdmi_i/frequency_input_0_RnM/frequency_input[13]} {hdmi_i/frequency_input_0_RnM/frequency_input[14]} {hdmi_i/frequency_input_0_RnM/frequency_input[15]}]]
set_property src_info {type:XDC file:2 line:511 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:521 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list hdmi_i/mig_7series_0/u_hdmi_mig_7series_0_0_mig/u_ddr3_infrastructure/gen_ui_extra_clocks.mmcm_i_0]]
set_property src_info {type:XDC file:2 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:524 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {hdmi_i/frequency_input_0_RnM/frequency_input[0]} {hdmi_i/frequency_input_0_RnM/frequency_input[1]} {hdmi_i/frequency_input_0_RnM/frequency_input[2]} {hdmi_i/frequency_input_0_RnM/frequency_input[3]} {hdmi_i/frequency_input_0_RnM/frequency_input[4]} {hdmi_i/frequency_input_0_RnM/frequency_input[5]} {hdmi_i/frequency_input_0_RnM/frequency_input[6]} {hdmi_i/frequency_input_0_RnM/frequency_input[7]} {hdmi_i/frequency_input_0_RnM/frequency_input[8]} {hdmi_i/frequency_input_0_RnM/frequency_input[9]} {hdmi_i/frequency_input_0_RnM/frequency_input[10]} {hdmi_i/frequency_input_0_RnM/frequency_input[11]} {hdmi_i/frequency_input_0_RnM/frequency_input[12]} {hdmi_i/frequency_input_0_RnM/frequency_input[13]} {hdmi_i/frequency_input_0_RnM/frequency_input[14]} {hdmi_i/frequency_input_0_RnM/frequency_input[15]}]]
set_property src_info {type:XDC file:2 line:525 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:528 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {hdmi_i/frequency_input_0_RnM/s00_axi_awaddr[2]} {hdmi_i/frequency_input_0_RnM/s00_axi_awaddr[3]}]]
set_property src_info {type:XDC file:2 line:529 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:532 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[0]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[1]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[2]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[3]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[4]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[5]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[6]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[7]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[8]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[9]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[10]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[11]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[12]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[13]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[14]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[15]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[16]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[17]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[18]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[19]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[20]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[21]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[22]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[23]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[24]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[25]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[26]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[27]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[28]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[29]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[30]} {hdmi_i/frequency_input_0_RnM/s00_axi_wdata[31]}]]
set_property src_info {type:XDC file:2 line:533 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:536 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {hdmi_i/frequency_input_0_RnM/s00_axi_araddr[2]} {hdmi_i/frequency_input_0_RnM/s00_axi_araddr[3]}]]
set_property src_info {type:XDC file:2 line:537 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:540 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[0]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[1]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[2]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[3]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[4]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[5]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[6]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[7]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[8]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[9]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[10]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[11]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[12]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[13]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[14]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[15]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[16]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[17]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[18]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[19]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[20]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[21]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[22]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[23]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[24]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[25]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[26]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[27]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[28]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[29]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[30]} {hdmi_i/frequency_input_0_RnM/s00_axi_rdata[31]}]]
set_property src_info {type:XDC file:2 line:541 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:544 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list hdmi_i/microblaze_0_axi_periph_M08_AXI_ARREADY]]
set_property src_info {type:XDC file:2 line:545 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:548 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list hdmi_i/microblaze_0_axi_periph_M08_AXI_ARVALID]]
set_property src_info {type:XDC file:2 line:549 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:552 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list hdmi_i/microblaze_0_axi_periph_M08_AXI_AWREADY]]
set_property src_info {type:XDC file:2 line:553 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:556 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list hdmi_i/microblaze_0_axi_periph_M08_AXI_AWVALID]]
set_property src_info {type:XDC file:2 line:557 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:560 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list hdmi_i/microblaze_0_axi_periph_M08_AXI_BREADY]]
set_property src_info {type:XDC file:2 line:561 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:564 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list hdmi_i/microblaze_0_axi_periph_M08_AXI_BVALID]]
set_property src_info {type:XDC file:2 line:565 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:566 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:568 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list hdmi_i/microblaze_0_axi_periph_M08_AXI_RREADY]]
set_property src_info {type:XDC file:2 line:569 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:570 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:572 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list hdmi_i/microblaze_0_axi_periph_M08_AXI_RVALID]]
set_property src_info {type:XDC file:2 line:573 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:576 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list hdmi_i/microblaze_0_axi_periph_M08_AXI_WREADY]]
set_property src_info {type:XDC file:2 line:577 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:580 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list hdmi_i/microblaze_0_axi_periph_M08_AXI_WVALID]]
set_property src_info {type:XDC file:2 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:582 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:584 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
