# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_1/bd_7c6c_v_tc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7c6c_v_tc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_1/bd_7c6c_v_tc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7c6c_v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_1/bd_7c6c_v_tc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7c6c_v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jason/ECE532/ECE532-project/HDMI_Example_Design/HDMI_Example_Design.srcs/sources_1/ip/HDMI_Transmitter_sub/bd_0/ip/ip_1/bd_7c6c_v_tc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7c6c_v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
