# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ECE532/fft_project/fft_project/fft_project.srcs/sources_1/bd/DSP/ip/DSP_xbip_dsp48_macro_0_0/DSP_xbip_dsp48_macro_0_0.xci
# IP: The module: 'DSP_xbip_dsp48_macro_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE532/fft_project/fft_project/fft_project.srcs/sources_1/bd/DSP/ip/DSP_xbip_dsp48_macro_0_0/DSP_xbip_dsp48_macro_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP_xbip_dsp48_macro_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/ECE532/fft_project/fft_project/fft_project.srcs/sources_1/bd/DSP/ip/DSP_xbip_dsp48_macro_0_0/DSP_xbip_dsp48_macro_0_0.xci
# IP: The module: 'DSP_xbip_dsp48_macro_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE532/fft_project/fft_project/fft_project.srcs/sources_1/bd/DSP/ip/DSP_xbip_dsp48_macro_0_0/DSP_xbip_dsp48_macro_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP_xbip_dsp48_macro_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
