# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MEM_I/MEM_I.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MEM_I || ORIG_REF_NAME==MEM_I} -quiet] -quiet

# IP: bd/MEM_I/ip/MEM_I_axi_bram_ctrl_0_bram_0/MEM_I_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MEM_I_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==MEM_I_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: bd/MEM_I/MEM_I_ooc.xdc
