@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Mar 09 20:50:36 -0500 2024
REM SW Build 2489853 on Tue Mar 26 04:20:25 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim spi_mic_tb_behav -key {Behavioral:sim_1:Functional:spi_mic_tb} -tclbatch spi_mic_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/robita46/ECE532-project-main/ECE532-project-main/Trumpet_project/project_1/i2c_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
