@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< Updated upstream
REM Generated by Vivado on Wed Mar 06 02:30:58 -0500 2024
=======
REM Generated by Vivado on Fri Mar 22 13:23:44 -0400 2024
>>>>>>> Stashed changes
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
<<<<<<< Updated upstream
call xsim addr_gen_tb_behav -key {Behavioral:sim_1:Functional:addr_gen_tb} -tclbatch addr_gen_tb.tcl -protoinst "protoinst_files/MEM_I.protoinst" -protoinst "protoinst_files/DSP.protoinst" -view C:/ECE532/fft_project/fft_project/addr_gen_tb_behav.wcfg -log simulate.log
=======
call xsim addr_gen_tb_behav -key {Behavioral:sim_1:Functional:addr_gen_tb} -tclbatch addr_gen_tb.tcl -protoinst "protoinst_files/MEM_I.protoinst" -view C:/ECE532/fft_project/fft_project/addr_gen_tb_behav.wcfg -log simulate.log
>>>>>>> Stashed changes
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
